### ISSUE TITLE
Visualize data

### ISSUE THREAD

**Issue by Tommos0** [GlamGeoVis/GlamGeoMap#6]
Create a visualization layer on the map that shows, based on books data:
* Glyphs @ locatio on map
* Glyph should look like previous implementation's Glyph
* Glyph represents library or cluster of libraries
* Glyph is scaled as a function of the number of books
* Glyph contains different colors, area represents number of books per time period

**Comment by c-martinez** [comment]
Glyphs at location should be drawn based on the data sent as per #8.
